###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: docker-mercure-mysql
      working_dir: /application
      volumes:
        - ./backend:/application
      environment:
        - MYSQL_ROOT_PASSWORD=dbrootpw
        - MYSQL_DATABASE=docker_symfony4
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpw
      ports:
        - "3306:3306"
      networks:
            docker-mercure-network:
                ipv4_address: 172.99.0.2
    webserver:
      image: nginx:alpine
      container_name: docker-mercure-webserver
      working_dir: /application
      volumes:
          - ./backend:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
      networks:
            docker-mercure-network:
                ipv4_address: 172.99.0.3
    php-fpm:
      build: phpdocker/php-fpm
      container_name: docker-mercure-php-fpm
      working_dir: /application
      volumes:
        - ./backend:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      networks:
            docker-mercure-network:
                ipv4_address: 172.99.0.4
    mercure:
      image: dunglas/mercure:latest
      container_name: docker-mercure-hub
      environment:
      - JWT_KEY=myJWTKey
      - DEMO=1
      - ALLOW_ANONYMOUS=1
      - PUBLISH_ALLOWED_ORIGINS=http://localhost:3000
      - ADDR=:3000
      - DEBUG=1
      - CORS_ALLOWED_ORIGINS=*
      ports:
       - "3000:3000"
      networks:
            docker-mercure-network:
                ipv4_address: 172.99.0.5

networks:
    docker-mercure-network:
        ipam:
          config:
            - subnet: 172.99.0.0/16
